"Compiled on a Linux 3.0.65 system on 2014-01-21.\n"
"Available extensions:\n"
"	crypt add-on version 2.1 by Michael Glad and others\n"
"	GNU Libidn by Simon Josefsson\n"
"	Native POSIX Threads Library by Ulrich Drepper et al\n"
"	BIND-8.2.3-T5B\n"
