files="1
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libutil.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/libm.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/ld.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libnsl.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libthread_db.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libresolv.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libanl.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libpthread.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libc.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libdl.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libcrypt.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/libBrokenLocale.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
abilist/librt.abilist
aclocal.m4
aclocal.m4
aclocal.m4
Binary file a.out matches
argp/Versions
assert/Versions
assert/Versions
autom4te.cache/traces.0
autom4te.cache/traces.0
autom4te.cache/output.0
bits/types.h
bits/types.h
catgets/Versions
catgets/Versions
ChangeLog
ChangeLog
ChangeLog
ChangeLog
ChangeLog
ChangeLog
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.10
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.11
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.12
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.13
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.14
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.15
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.16
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.17
ChangeLog.2
ChangeLog.6
ChangeLog.6
ChangeLog.7
ChangeLog.7
ChangeLog.7
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.8
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
ChangeLog.9
config.h.in
configure
configure.in
crypt/Versions
csu/errno.c
csu/errno.c
csu/Versions
csu/Versions
csu/Versions
csu/Versions
csu/version.c
csu/version.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/ctype-info.c
ctype/Versions
ctype/Versions
ctype/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
debug/Versions
dirent/Versions
dirent/Versions
dirent/Versions
dirent/Versions
dlfcn/dlopen.c
dlfcn/tststatic2.c
dlfcn/Versions
dlfcn/Versions
dlfcn/Versions
dlfcn/Versions
dlfcn/Versions
dlfcn/dlopenold.c
dlfcn/dlopenold.c
dlfcn/modstatic2.c
elf/dl-libc.c
elf/Versions
elf/Versions
elf/Versions
elf/Versions
elf/Versions
elf/Versions
elf/Versions
elf/Versions
elf/Versions
gmon/Versions
gmon/Versions
gmon/Versions
grp/Versions
grp/Versions
grp/Versions
grp/Versions
gshadow/Versions
hesiod/Versions
hurd/compat-20.c
hurd/compat-20.c
hurd/compat-20.c
hurd/hurdinit.c
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Versions
hurd/Makefile
iconv/Versions
iconv/Versions
Binary file iconv/a.out matches
include/features.h
include/features.h
include/features.h
include/features.h
include/features.h
include/features.h
include/features.h
include/features.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/shlib-compat.h
include/libc-symbols.h
inet/herrno.c
inet/herrno.c
inet/Versions
inet/Versions
inet/Versions
inet/Versions
inet/Versions
inet/Versions
inet/Versions
inet/Versions
inet/Versions
intl/plural.c
intl/plural.c
intl/dcigettext.c
intl/loadmsgcat.c
intl/Versions
intl/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/Versions
io/ftw.c
io/ftw.c
io/ftw.c
libidn/configure.in
libidn/Versions
libio/iofdopen.c
libio/iofdopen.c
libio/oldiofsetpos.c
libio/oldiofsetpos.c
libio/oldiofsetpos.c
libio/oldiofopen.c
libio/oldiofopen.c
libio/oldiofopen.c
libio/oldiofclose.c
libio/oldiofclose.c
libio/oldiofclose.c
libio/iofgetpos64.c
libio/iofgetpos64.c
libio/libioP.h
libio/libioP.h
libio/libioP.h
libio/libioP.h
libio/libioP.h
libio/libio.h
libio/libio.h
libio/libio.h
libio/libio.h
libio/libio.h
libio/libio.h
libio/libio.h
libio/iofwide.c
libio/iofwide.c
libio/iofwide.c
libio/iofwide.c
libio/iofwide.c
libio/iofwide.c
libio/iofopncook.c
libio/iofopncook.c
libio/iofopncook.c
libio/oldtmpfile.c
libio/oldtmpfile.c
libio/freopen.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/fileops.c
libio/iofclose.c
libio/iofclose.c
libio/iofclose.c
libio/oldiopopen.c
libio/oldiopopen.c
libio/oldiopopen.c
libio/oldiopopen.c
libio/oldiopopen.c
libio/genops.c
libio/genops.c
libio/genops.c
libio/genops.c
libio/pclose.c
libio/oldiofgetpos64.c
libio/oldiofgetpos64.c
libio/oldiofgetpos64.c
libio/oldstdfiles.c
libio/iofsetpos64.c
libio/iofsetpos64.c
libio/iopopen.c
libio/iopopen.c
libio/iopopen.c
libio/iopopen.c
libio/oldpclose.c
libio/oldpclose.c
libio/oldiofgetpos.c
libio/oldiofgetpos.c
libio/oldiofgetpos.c
libio/iofgetpos.c
libio/iofgetpos.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldfileops.c
libio/oldiofdopen.c
libio/oldiofdopen.c
libio/oldiofdopen.c
libio/Versions
libio/Versions
libio/Versions
libio/Versions
libio/Versions
libio/oldiofsetpos64.c
libio/oldiofsetpos64.c
libio/oldiofsetpos64.c
libio/iofopen.c
libio/iofopen.c
libio/iofopen.c
libio/iofsetpos.c
libio/iofsetpos.c
libio/stdfiles.c
libio/stdfiles.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/lc-ctype.c
locale/localeconv.c
locale/localeconv.c
locale/localeconv.c
locale/Versions
locale/Versions
locale/Versions
locale/Versions
locale/Versions
locale/Versions
login/Versions
login/Versions
login/Versions
login/Versions
login/Versions
mach/Versions
mach/Versions
mach/Versions
mach/Versions
mach/Versions
Makeconfig
malloc/obstack.c
malloc/obstack.c
malloc/Versions
malloc/Versions
malloc/Versions
malloc/Versions
malloc/Versions
manual/maint.texi
math/fegetenv.c
math/fegetenv.c
math/fegetenv.c
math/fclrexcpt.c
math/fclrexcpt.c
math/fclrexcpt.c
math/feupdateenv.c
math/feupdateenv.c
math/feupdateenv.c
math/fsetexcptflg.c
math/fsetexcptflg.c
math/fsetexcptflg.c
math/fraiseexcpt.c
math/fraiseexcpt.c
math/fraiseexcpt.c
math/Versions
math/Versions
math/Versions
math/Versions
math/Versions
math/Versions
math/Versions
math/Versions
math/Versions
math/fgetexcptflg.c
math/fgetexcptflg.c
math/fgetexcptflg.c
math/fesetenv.c
math/fesetenv.c
math/fesetenv.c
misc/efgcvt.c
misc/efgcvt.c
misc/efgcvt.c
misc/efgcvt_r.c
misc/efgcvt_r.c
misc/efgcvt_r.c
misc/sys/cdefs.h
misc/Versions
misc/Versions
misc/Versions
misc/Versions
misc/Versions
misc/Versions
misc/Versions
misc/Versions
misc/Versions
nis/Versions
nis/Versions
nis/Versions
nis/Versions
nis/Versions
nis/Versions
nis/Versions
nptl/old_pthread_cond_timedwait.c
nptl/old_pthread_cond_timedwait.c
nptl/pthread_create.c
nptl/pthread_create.c
nptl/pthread_create.c
nptl/pthread_attr_setstack.c
nptl/pthread_attr_setstack.c
nptl/pthread_attr_setstack.c
nptl/old_pthread_cond_wait.c
nptl/old_pthread_cond_wait.c
nptl/pthread_cond_init.c
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/ChangeLog
nptl/old_pthread_cond_destroy.c
nptl/old_pthread_cond_destroy.c
nptl/sem_init.c
nptl/sem_init.c
nptl/sem_init.c
nptl/old_pthread_atfork.c
nptl/old_pthread_atfork.c
nptl/pthread_cond_wait.c
nptl/pthread_attr_init.c
nptl/pthread_attr_init.c
nptl/pthread_attr_init.c
nptl/sem_getvalue.c
nptl/sem_getvalue.c
nptl/sem_getvalue.c
nptl/pthread_kill_other_threads.c
nptl/pthread_cond_destroy.c
nptl/pthread_cond_signal.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/forward.c
nptl/old_pthread_cond_signal.c
nptl/old_pthread_cond_signal.c
nptl/pthread_cond_timedwait.c
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/shlib-versions
nptl/sem_destroy.c
nptl/sem_destroy.c
nptl/sem_destroy.c
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/Versions
nptl/nptl-init.c
nptl/nptl-init.c
nptl/pthread_attr_setstacksize.c
nptl/pthread_attr_setstacksize.c
nptl/pthread_attr_setstacksize.c
nptl/old_pthread_cond_broadcast.c
nptl/old_pthread_cond_broadcast.c
nptl/sysdeps/pthread/configure.in
nptl/sysdeps/x86_64/configure.in
nptl/sysdeps/unix/sysv/linux/sparc/sem_init.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_init.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_init.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc64/Versions
nptl/sysdeps/unix/sysv/linux/sparc/aio_cancel.c
nptl/sysdeps/unix/sysv/linux/sparc/aio_cancel.c
nptl/sysdeps/unix/sysv/linux/sparc/aio_cancel.c
nptl/sysdeps/unix/sysv/linux/sparc/aio_cancel.c
nptl/sysdeps/unix/sysv/linux/sparc/aio_cancel.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sparc/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sparc/Versions
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_post.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sparc/sparc32/sem_wait.c
nptl/sysdeps/unix/sysv/linux/pthread_attr_setaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_attr_setaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_attr_setaffinity.c
nptl/sysdeps/unix/sysv/linux/i386/i486/pthread_cond_broadcast.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_trywait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_trywait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_trywait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/pthread_cond_timedwait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/pthread_cond_wait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_post.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_post.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_post.S
nptl/sysdeps/unix/sysv/linux/i386/i486/pthread_cond_signal.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_wait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_wait.S
nptl/sysdeps/unix/sysv/linux/i386/i486/sem_wait.S
nptl/sysdeps/unix/sysv/linux/pthread_getaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_getaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_getaffinity.c
nptl/sysdeps/unix/sysv/linux/powerpc/pthread_attr_setstack.c
nptl/sysdeps/unix/sysv/linux/powerpc/sem_post.c
nptl/sysdeps/unix/sysv/linux/powerpc/sem_post.c
nptl/sysdeps/unix/sysv/linux/powerpc/sem_post.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/pt-longjmp.c
nptl/sysdeps/unix/sysv/linux/powerpc/Versions
nptl/sysdeps/unix/sysv/linux/powerpc/Versions
nptl/sysdeps/unix/sysv/linux/powerpc/pthread_attr_setstacksize.c
nptl/sysdeps/unix/sysv/linux/powerpc/powerpc64/Versions
nptl/sysdeps/unix/sysv/linux/sh/pthread_cond_broadcast.S
nptl/sysdeps/unix/sysv/linux/sh/sem_trywait.S
nptl/sysdeps/unix/sysv/linux/sh/pthread_cond_timedwait.S
nptl/sysdeps/unix/sysv/linux/sh/pthread_cond_wait.S
nptl/sysdeps/unix/sysv/linux/sh/sem_post.S
nptl/sysdeps/unix/sysv/linux/sh/pthread_cond_signal.S
nptl/sysdeps/unix/sysv/linux/sh/sem_wait.S
nptl/sysdeps/unix/sysv/linux/pthread_attr_getaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_attr_getaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_attr_getaffinity.c
nptl/sysdeps/unix/sysv/linux/s390/s390-64/Versions
nptl/sysdeps/unix/sysv/linux/x86_64/timer_create.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_create.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_create.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_settime.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_settime.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_settime.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_getoverr.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_getoverr.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_getoverr.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_gettime.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_gettime.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_gettime.c
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_broadcast.S
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S
nptl/sysdeps/unix/sysv/linux/x86_64/timer_delete.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_delete.c
nptl/sysdeps/unix/sysv/linux/x86_64/timer_delete.c
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S
nptl/sysdeps/unix/sysv/linux/x86_64/Versions
nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_signal.S
nptl/sysdeps/unix/sysv/linux/pthread_setaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_setaffinity.c
nptl/sysdeps/unix/sysv/linux/pthread_setaffinity.c
nptl/sysdeps/unix/sysv/linux/sem_post.c
nptl/sysdeps/unix/sysv/linux/sem_post.c
nptl/sysdeps/unix/sysv/linux/sem_post.c
nptl/sysdeps/unix/sysv/linux/ia64/Versions
nptl/sysdeps/unix/sysv/linux/ia64/Versions
nptl/sysdeps/unix/sysv/linux/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sem_trywait.c
nptl/sysdeps/unix/sysv/linux/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sem_wait.c
nptl/sysdeps/unix/sysv/linux/sem_wait.c
nptl/sysdeps/unix/sysv/linux/Versions
nptl/sysdeps/unix/sysv/linux/Versions
nptl/sysdeps/unix/sysv/linux/Versions
nptl/old_pthread_cond_init.c
nptl/old_pthread_cond_init.c
nptl/pthread_cond_broadcast.c
nptl/pthread_attr_destroy.c
nptl_db/ChangeLog
nptl_db/Versions
nptl_db/Versions
nptl_db/Versions
nptl_db/Versions
nss/getXXbyYY_r.c
nss/getXXbyYY_r.c
nss/getXXbyYY_r.c
nss/getXXbyYY_r.c
nss/getXXent_r.c
nss/getXXent_r.c
nss/getXXent_r.c
nss/getXXent_r.c
nss/Versions
nss/Versions
nss/Versions
nss/Versions
posix/getopt.c
posix/fnmatch.c
posix/fnmatch.c
posix/fnmatch.c
Binary file posix/.Versions.swp matches
posix/regex.c
posix/sys/types.h
posix/sys/types.h
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/Versions
posix/regexec.c
posix/regexec.c
posix/regexec.c
posix/getopt1.c
pwd/Versions
pwd/Versions
resolv/res_comp.c
resolv/res_data.c
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/Versions
resolv/res_libc.c
resolv/res_libc.c
resolv/res_libc.c
resource/Versions
resource/Versions
rt/Versions
rt/Versions
rt/Versions
rt/Versions
run.sh
scripts/config.guess
scripts/config.guess
scripts/firstversions.awk
scripts/abilist.awk
scripts/abi-versions.awk
scripts/abi-versions.awk
scripts/merge-abilist.awk
scripts/merge-abilist.awk
scripts/merge-abilist.awk
scripts/versions.awk
scripts/versions.awk
scripts/versions.awk
scripts/versions.awk
scripts/versions.awk
scripts/extract-abilist.awk
scripts/extract-abilist.awk
scripts/extract-abilist.awk
setjmp/Versions
setjmp/Versions
shadow/Versions
shadow/Versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
shlib-versions
signal/Versions
signal/Versions
signal/Versions
signal/Versions
socket/Versions
socket/Versions
socket/Versions
stdio-common/tmpfile.c
stdio-common/Versions
stdio-common/Versions
stdio-common/Versions
stdio-common/Versions
stdio-common/Versions
stdio-common/Versions
stdlib/strtoull.c
stdlib/strtoull.c
stdlib/strtod_l.c
stdlib/strtod_l.c
stdlib/strtod_l.c
stdlib/strtod_l.c
stdlib/strtod_l.c
stdlib/strtod_l.c
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/tst-fmtmsg.sh
stdlib/strtoll.c
stdlib/strtoll.c
stdlib/stdlib.h
stdlib/stdlib.h
stdlib/stdlib.h
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/tst-fmtmsg.c
stdlib/canonicalize.c
stdlib/canonicalize.c
stdlib/canonicalize.c
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/Versions
stdlib/strtod.c
stdlib/strtod.c
stdlib/strtod.c
stdlib/strtod.c
stdlib/strtod.c
stdlib/old_atexit.c
stdlib/old_atexit.c
streams/Versions
string/Versions
string/Versions
string/Versions
string/Versions
string/Versions
string/Versions
sunrpc/Versions
sunrpc/Versions
sunrpc/Versions
sunrpc/Versions
sunrpc/Versions
sunrpc/Versions
sunrpc/Versions
sysdeps/sparc/sparc64/elf/configure.in
sysdeps/sparc/sparc64/Versions
sysdeps/sparc/sparc64/Versions
sysdeps/sparc/sparc64/soft-fp/Versions
sysdeps/sparc/fpu/fegetenv.c
sysdeps/sparc/fpu/fegetenv.c
sysdeps/sparc/fpu/fegetenv.c
sysdeps/sparc/fpu/fclrexcpt.c
sysdeps/sparc/fpu/fclrexcpt.c
sysdeps/sparc/fpu/fclrexcpt.c
sysdeps/sparc/fpu/feupdateenv.c
sysdeps/sparc/fpu/feupdateenv.c
sysdeps/sparc/fpu/feupdateenv.c
sysdeps/sparc/fpu/fsetexcptflg.c
sysdeps/sparc/fpu/fsetexcptflg.c
sysdeps/sparc/fpu/fsetexcptflg.c
sysdeps/sparc/fpu/fraiseexcpt.c
sysdeps/sparc/fpu/fraiseexcpt.c
sysdeps/sparc/fpu/fraiseexcpt.c
sysdeps/sparc/fpu/fgetexcptflg.c
sysdeps/sparc/fpu/fgetexcptflg.c
sysdeps/sparc/fpu/fgetexcptflg.c
sysdeps/sparc/fpu/fesetenv.c
sysdeps/sparc/fpu/fesetenv.c
sysdeps/sparc/fpu/fesetenv.c
sysdeps/sparc/sparc32/elf/configure.in
sysdeps/sparc/sparc32/Versions
sysdeps/sparc/sparc32/fpu/s_fabs.c
sysdeps/sparc/sparc32/fpu/s_fabs.c
sysdeps/sparc/sparc32/soft-fp/Versions
sysdeps/i386/i486/Versions
sysdeps/i386/configure.in
sysdeps/i386/i686/multiarch/Versions
sysdeps/i386/elf/configure.in
sysdeps/i386/elf/Versions
sysdeps/i386/Versions
sysdeps/i386/Versions
sysdeps/i386/Versions
sysdeps/i386/Versions
sysdeps/i386/fpu/fegetenv.c
sysdeps/i386/fpu/fegetenv.c
sysdeps/i386/fpu/fegetenv.c
sysdeps/i386/fpu/fclrexcpt.c
sysdeps/i386/fpu/fclrexcpt.c
sysdeps/i386/fpu/fclrexcpt.c
sysdeps/i386/fpu/feupdateenv.c
sysdeps/i386/fpu/feupdateenv.c
sysdeps/i386/fpu/feupdateenv.c
sysdeps/i386/fpu/fsetexcptflg.c
sysdeps/i386/fpu/fsetexcptflg.c
sysdeps/i386/fpu/fsetexcptflg.c
sysdeps/i386/fpu/fraiseexcpt.c
sysdeps/i386/fpu/fraiseexcpt.c
sysdeps/i386/fpu/fraiseexcpt.c
sysdeps/i386/fpu/Versions
sysdeps/i386/fpu/fgetexcptflg.c
sysdeps/i386/fpu/fgetexcptflg.c
sysdeps/i386/fpu/fgetexcptflg.c
sysdeps/i386/fpu/fesetenv.c
sysdeps/i386/fpu/fesetenv.c
sysdeps/i386/fpu/fesetenv.c
sysdeps/wordsize-64/iofgetpos.c
sysdeps/wordsize-64/iofgetpos.c
sysdeps/wordsize-64/Versions
sysdeps/wordsize-64/iofsetpos.c
sysdeps/wordsize-64/iofsetpos.c
sysdeps/wordsize-64/ftw.c
sysdeps/wordsize-64/ftw.c
sysdeps/wordsize-64/ftw.c
sysdeps/pthread/lio_listio.c
sysdeps/pthread/lio_listio.c
sysdeps/pthread/lio_listio.c
sysdeps/pthread/lio_listio.c
sysdeps/pthread/Versions
sysdeps/mach/configure.in
sysdeps/mach/hurd/i386/Versions
sysdeps/mach/hurd/i386/Versions
sysdeps/mach/hurd/configure.in
sysdeps/mach/hurd/siglist.h
sysdeps/mach/hurd/tmpfile.c
sysdeps/mach/hurd/_G_config.h
sysdeps/mach/hurd/_G_config.h
sysdeps/mach/hurd/_G_config.h
sysdeps/mach/hurd/getclktck.c
sysdeps/mach/hurd/getclktck.c
sysdeps/mach/hurd/Versions
sysdeps/mach/hurd/Versions
sysdeps/mach/hurd/Versions
sysdeps/mach/hurd/Versions
sysdeps/mach/hurd/Versions
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/novmx-longjmp.c
sysdeps/powerpc/configure.in
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/libgcc-compat.S
sysdeps/powerpc/powerpc32/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc32/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc32/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_floor.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_floor.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_lround.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_lround.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_round.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_round.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_trunc.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_trunc.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_ceil.S
sysdeps/powerpc/powerpc32/power5+/fpu/s_ceil.S
sysdeps/powerpc/powerpc32/power6x/fpu/s_lround.S
sysdeps/powerpc/powerpc32/power6x/fpu/s_lround.S
sysdeps/powerpc/powerpc32/power6x/fpu/s_lrint.S
sysdeps/powerpc/powerpc32/power6x/fpu/s_lrint.S
sysdeps/powerpc/powerpc32/configure.in
sysdeps/powerpc/powerpc32/bsd-_setjmp.S
sysdeps/powerpc/powerpc32/bsd-_setjmp.S
sysdeps/powerpc/powerpc32/bsd-_setjmp.S
sysdeps/powerpc/powerpc32/bsd-_setjmp.S
sysdeps/powerpc/powerpc32/power5/fpu/w_sqrt.S
sysdeps/powerpc/powerpc32/power5/fpu/w_sqrt.S
sysdeps/powerpc/powerpc32/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/bsd-setjmp.S
sysdeps/powerpc/powerpc32/bsd-setjmp.S
sysdeps/powerpc/powerpc32/bsd-setjmp.S
sysdeps/powerpc/powerpc32/bsd-setjmp.S
sysdeps/powerpc/powerpc32/setjmp.S
sysdeps/powerpc/powerpc32/setjmp.S
sysdeps/powerpc/powerpc32/setjmp.S
sysdeps/powerpc/powerpc32/power4/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power4/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power4/fpu/w_sqrt.S
sysdeps/powerpc/powerpc32/power4/fpu/w_sqrt.S
sysdeps/powerpc/powerpc32/power4/fpu/s_llrint.S
sysdeps/powerpc/powerpc32/power4/fpu/s_llrint.S
sysdeps/powerpc/powerpc32/elf/configure.in
sysdeps/powerpc/powerpc32/Versions
sysdeps/powerpc/powerpc32/Versions
sysdeps/powerpc/powerpc32/power6/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power6/fpu/s_llround.S
sysdeps/powerpc/powerpc32/power6/fpu/s_llrint.S
sysdeps/powerpc/powerpc32/power6/fpu/s_llrint.S
sysdeps/powerpc/powerpc32/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/fpu/s_floor.S
sysdeps/powerpc/powerpc32/fpu/s_floor.S
sysdeps/powerpc/powerpc32/fpu/s_fdim.c
sysdeps/powerpc/powerpc32/fpu/s_fdim.c
sysdeps/powerpc/powerpc32/fpu/s_lround.S
sysdeps/powerpc/powerpc32/fpu/s_lround.S
sysdeps/powerpc/powerpc32/fpu/s_lrint.S
sysdeps/powerpc/powerpc32/fpu/s_lrint.S
sysdeps/powerpc/powerpc32/fpu/s_fabs.S
sysdeps/powerpc/powerpc32/fpu/s_fabs.S
sysdeps/powerpc/powerpc32/fpu/s_rint.S
sysdeps/powerpc/powerpc32/fpu/s_rint.S
sysdeps/powerpc/powerpc32/fpu/s_fmax.S
sysdeps/powerpc/powerpc32/fpu/s_fmax.S
sysdeps/powerpc/powerpc32/fpu/s_round.S
sysdeps/powerpc/powerpc32/fpu/s_round.S
sysdeps/powerpc/powerpc32/fpu/s_fma.S
sysdeps/powerpc/powerpc32/fpu/s_fma.S
sysdeps/powerpc/powerpc32/fpu/setjmp.S
sysdeps/powerpc/powerpc32/fpu/setjmp.S
sysdeps/powerpc/powerpc32/fpu/setjmp.S
sysdeps/powerpc/powerpc32/fpu/s_trunc.S
sysdeps/powerpc/powerpc32/fpu/s_trunc.S
sysdeps/powerpc/powerpc32/fpu/s_llrint.c
sysdeps/powerpc/powerpc32/fpu/s_llrint.c
sysdeps/powerpc/powerpc32/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/fpu/s_copysign.S
sysdeps/powerpc/powerpc32/fpu/s_fmin.S
sysdeps/powerpc/powerpc32/fpu/s_fmin.S
sysdeps/powerpc/powerpc32/fpu/s_ceil.S
sysdeps/powerpc/powerpc32/fpu/s_ceil.S
sysdeps/powerpc/powerpc32/fpu/__longjmp.S
sysdeps/powerpc/powerpc32/fpu/__longjmp.S
sysdeps/powerpc/powerpc32/fpu/__longjmp.S
sysdeps/powerpc/powerpc32/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/fpu/s_isnan.S
sysdeps/powerpc/powerpc32/__longjmp.S
sysdeps/powerpc/novmx-sigjmp.c
sysdeps/powerpc/novmx-sigjmp.c
sysdeps/powerpc/Versions
sysdeps/powerpc/Versions
sysdeps/powerpc/Versions
sysdeps/powerpc/fpu/fegetenv.c
sysdeps/powerpc/fpu/fegetenv.c
sysdeps/powerpc/fpu/fegetenv.c
sysdeps/powerpc/fpu/fclrexcpt.c
sysdeps/powerpc/fpu/fclrexcpt.c
sysdeps/powerpc/fpu/fclrexcpt.c
sysdeps/powerpc/fpu/feupdateenv.c
sysdeps/powerpc/fpu/feupdateenv.c
sysdeps/powerpc/fpu/feupdateenv.c
sysdeps/powerpc/fpu/fsetexcptflg.c
sysdeps/powerpc/fpu/fsetexcptflg.c
sysdeps/powerpc/fpu/fsetexcptflg.c
sysdeps/powerpc/fpu/fraiseexcpt.c
sysdeps/powerpc/fpu/fraiseexcpt.c
sysdeps/powerpc/fpu/fraiseexcpt.c
sysdeps/powerpc/fpu/fgetexcptflg.c
sysdeps/powerpc/fpu/fgetexcptflg.c
sysdeps/powerpc/fpu/fgetexcptflg.c
sysdeps/powerpc/fpu/fesetenv.c
sysdeps/powerpc/fpu/fesetenv.c
sysdeps/powerpc/fpu/fesetenv.c
sysdeps/powerpc/soft-fp/Versions
sysdeps/powerpc/longjmp.c
sysdeps/powerpc/longjmp.c
sysdeps/powerpc/longjmp.c
sysdeps/powerpc/longjmp.c
sysdeps/powerpc/longjmp.c
sysdeps/powerpc/powerpc64/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc64/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc64/power7/fpu/s_finite.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isinf.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power7/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_floor.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_floor.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_round.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_round.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_trunc.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_trunc.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_ceil.S
sysdeps/powerpc/powerpc64/power5+/fpu/s_ceil.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llround.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power6x/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/configure.in
sysdeps/powerpc/powerpc64/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power5/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/setjmp.S
sysdeps/powerpc/powerpc64/power4/fpu/w_sqrt.c
sysdeps/powerpc/powerpc64/power4/fpu/w_sqrt.c
sysdeps/powerpc/powerpc64/elf/configure.in
sysdeps/powerpc/powerpc64/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/power6/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/power6/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/fpu/s_llround.S
sysdeps/powerpc/powerpc64/fpu/s_llround.S
sysdeps/powerpc/powerpc64/fpu/s_llround.S
sysdeps/powerpc/powerpc64/fpu/s_floor.S
sysdeps/powerpc/powerpc64/fpu/s_floor.S
sysdeps/powerpc/powerpc64/fpu/s_fdim.c
sysdeps/powerpc/powerpc64/fpu/s_fdim.c
sysdeps/powerpc/powerpc64/fpu/s_fabs.S
sysdeps/powerpc/powerpc64/fpu/s_fabs.S
sysdeps/powerpc/powerpc64/fpu/s_rint.S
sysdeps/powerpc/powerpc64/fpu/s_rint.S
sysdeps/powerpc/powerpc64/fpu/s_fmax.S
sysdeps/powerpc/powerpc64/fpu/s_fmax.S
sysdeps/powerpc/powerpc64/fpu/s_round.S
sysdeps/powerpc/powerpc64/fpu/s_round.S
sysdeps/powerpc/powerpc64/fpu/s_fma.S
sysdeps/powerpc/powerpc64/fpu/s_fma.S
sysdeps/powerpc/powerpc64/fpu/s_trunc.S
sysdeps/powerpc/powerpc64/fpu/s_trunc.S
sysdeps/powerpc/powerpc64/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/fpu/s_llrint.S
sysdeps/powerpc/powerpc64/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/fpu/s_copysign.S
sysdeps/powerpc/powerpc64/fpu/s_fmin.S
sysdeps/powerpc/powerpc64/fpu/s_fmin.S
sysdeps/powerpc/powerpc64/fpu/s_ceil.S
sysdeps/powerpc/powerpc64/fpu/s_ceil.S
sysdeps/powerpc/powerpc64/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/fpu/s_isnan.S
sysdeps/powerpc/powerpc64/__longjmp.S
sysdeps/wordsize-32/Versions
sysdeps/wordsize-32/divdi3.c
sysdeps/wordsize-32/divdi3.c
sysdeps/wordsize-32/divdi3.c
sysdeps/wordsize-32/divdi3.c
sysdeps/generic/_G_config.h
sysdeps/generic/_G_config.h
sysdeps/generic/_G_config.h
sysdeps/generic/unwind-dw2-fde.c
sysdeps/generic/unwind-dw2-fde-glibc.c
sysdeps/generic/unwind-dw2-fde-glibc.c
sysdeps/generic/unwind-dw2-fde-glibc.c
sysdeps/sh/sh4/Versions
sysdeps/sh/elf/configure.in
sysdeps/s390/s390-32/elf/configure.in
sysdeps/s390/s390-32/Versions
sysdeps/s390/s390-64/elf/configure.in
sysdeps/s390/Versions
sysdeps/x86_64/elf/configure.in
sysdeps/x86_64/multiarch/Versions
sysdeps/x86_64/Versions
sysdeps/x86_64/fpu/feupdateenv.c
sysdeps/x86_64/fpu/feupdateenv.c
sysdeps/x86_64/fpu/feupdateenv.c
sysdeps/ia64/configure.in
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/ia64libgcc.S
sysdeps/ia64/elf/configure.in
sysdeps/ia64/Versions
sysdeps/ia64/Versions
sysdeps/ia64/Versions
sysdeps/ia64/fpu/Versions
sysdeps/ia64/fpu/Versions
sysdeps/ieee754/ldbl-opt/s_rint.c
sysdeps/ieee754/ldbl-opt/s_rint.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/nldbl-compat.c
sysdeps/ieee754/ldbl-opt/s_csinh.c
sysdeps/ieee754/ldbl-opt/s_csinh.c
sysdeps/ieee754/ldbl-opt/s_fabs.c
sysdeps/ieee754/ldbl-opt/s_fabs.c
sysdeps/ieee754/ldbl-opt/s_remquo.c
sysdeps/ieee754/ldbl-opt/s_remquo.c
sysdeps/ieee754/ldbl-opt/s_ceil.c
sysdeps/ieee754/ldbl-opt/s_ceil.c
sysdeps/ieee754/ldbl-opt/s_casin.c
sysdeps/ieee754/ldbl-opt/s_casin.c
sysdeps/ieee754/ldbl-opt/w_remainder.c
sysdeps/ieee754/ldbl-opt/w_remainder.c
sysdeps/ieee754/ldbl-opt/s_sin.c
sysdeps/ieee754/ldbl-opt/s_sin.c
sysdeps/ieee754/ldbl-opt/s_sin.c
sysdeps/ieee754/ldbl-opt/s_fdim.c
sysdeps/ieee754/ldbl-opt/s_fdim.c
sysdeps/ieee754/ldbl-opt/carg.c
sysdeps/ieee754/ldbl-opt/carg.c
sysdeps/ieee754/ldbl-opt/s_copysign.c
sysdeps/ieee754/ldbl-opt/s_copysign.c
sysdeps/ieee754/ldbl-opt/s_copysign.c
sysdeps/ieee754/ldbl-opt/s_copysign.c
sysdeps/ieee754/ldbl-opt/w_lgamma.c
sysdeps/ieee754/ldbl-opt/w_lgamma.c
sysdeps/ieee754/ldbl-opt/w_lgamma.c
sysdeps/ieee754/ldbl-opt/w_lgamma_r.c
sysdeps/ieee754/ldbl-opt/w_lgamma_r.c
sysdeps/ieee754/ldbl-opt/w_j1.c
sysdeps/ieee754/ldbl-opt/w_j1.c
sysdeps/ieee754/ldbl-opt/w_j1.c
sysdeps/ieee754/ldbl-opt/s_nan.c
sysdeps/ieee754/ldbl-opt/s_nan.c
sysdeps/ieee754/ldbl-opt/cimag.c
sysdeps/ieee754/ldbl-opt/cimag.c
sysdeps/ieee754/ldbl-opt/s_clog10.c
sysdeps/ieee754/ldbl-opt/s_clog10.c
sysdeps/ieee754/ldbl-opt/s_clog10.c
sysdeps/ieee754/ldbl-opt/s_cexp.c
sysdeps/ieee754/ldbl-opt/s_cexp.c
sysdeps/ieee754/ldbl-opt/w_log2.c
sysdeps/ieee754/ldbl-opt/w_log2.c
sysdeps/ieee754/ldbl-opt/w_j0.c
sysdeps/ieee754/ldbl-opt/w_j0.c
sysdeps/ieee754/ldbl-opt/w_j0.c
sysdeps/ieee754/ldbl-opt/w_log.c
sysdeps/ieee754/ldbl-opt/w_log.c
sysdeps/ieee754/ldbl-opt/s_frexp.c
sysdeps/ieee754/ldbl-opt/s_frexp.c
sysdeps/ieee754/ldbl-opt/s_frexp.c
sysdeps/ieee754/ldbl-opt/s_frexp.c
sysdeps/ieee754/ldbl-opt/w_sqrt.c
sysdeps/ieee754/ldbl-opt/w_sqrt.c
sysdeps/ieee754/ldbl-opt/s_clog.c
sysdeps/ieee754/ldbl-opt/s_clog.c
sysdeps/ieee754/ldbl-opt/configure.in
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/s_finite.c
sysdeps/ieee754/ldbl-opt/w_pow.c
sysdeps/ieee754/ldbl-opt/w_pow.c
sysdeps/ieee754/ldbl-opt/s_csqrt.c
sysdeps/ieee754/ldbl-opt/s_csqrt.c
sysdeps/ieee754/ldbl-opt/s_fmax.c
sysdeps/ieee754/ldbl-opt/s_fmax.c
sysdeps/ieee754/ldbl-opt/s_asinh.c
sysdeps/ieee754/ldbl-opt/s_asinh.c
sysdeps/ieee754/ldbl-opt/s_isnan.c
sysdeps/ieee754/ldbl-opt/s_isnan.c
sysdeps/ieee754/ldbl-opt/s_isnan.c
sysdeps/ieee754/ldbl-opt/s_ilogb.c
sysdeps/ieee754/ldbl-opt/s_ilogb.c
sysdeps/ieee754/ldbl-opt/s_expm1.c
sysdeps/ieee754/ldbl-opt/s_expm1.c
sysdeps/ieee754/ldbl-opt/s_cproj.c
sysdeps/ieee754/ldbl-opt/s_cproj.c
sysdeps/ieee754/ldbl-opt/s_fma.c
sysdeps/ieee754/ldbl-opt/s_fma.c
sysdeps/ieee754/ldbl-opt/s_lround.c
sysdeps/ieee754/ldbl-opt/s_lround.c
sysdeps/ieee754/ldbl-opt/s_ccos.c
sysdeps/ieee754/ldbl-opt/s_ccos.c
sysdeps/ieee754/ldbl-opt/s_nexttowardfd.c
sysdeps/ieee754/ldbl-opt/s_nexttowardfd.c
sysdeps/ieee754/ldbl-opt/s_cbrt.c
sysdeps/ieee754/ldbl-opt/s_cbrt.c
sysdeps/ieee754/ldbl-opt/creal.c
sysdeps/ieee754/ldbl-opt/creal.c
sysdeps/ieee754/ldbl-opt/s_floor.c
sysdeps/ieee754/ldbl-opt/s_floor.c
sysdeps/ieee754/ldbl-opt/w_exp10.c
sysdeps/ieee754/ldbl-opt/w_exp10.c
sysdeps/ieee754/ldbl-opt/w_exp10.c
sysdeps/ieee754/ldbl-opt/w_cosh.c
sysdeps/ieee754/ldbl-opt/w_cosh.c
sysdeps/ieee754/ldbl-opt/w_exp.c
sysdeps/ieee754/ldbl-opt/w_exp.c
sysdeps/ieee754/ldbl-opt/w_asin.c
sysdeps/ieee754/ldbl-opt/w_asin.c
sysdeps/ieee754/ldbl-opt/w_atan2.c
sysdeps/ieee754/ldbl-opt/w_atan2.c
sysdeps/ieee754/ldbl-opt/w_jn.c
sysdeps/ieee754/ldbl-opt/w_jn.c
sysdeps/ieee754/ldbl-opt/w_jn.c
sysdeps/ieee754/ldbl-opt/s_isinf.c
sysdeps/ieee754/ldbl-opt/s_isinf.c
sysdeps/ieee754/ldbl-opt/s_isinf.c
sysdeps/ieee754/ldbl-opt/s_csin.c
sysdeps/ieee754/ldbl-opt/s_csin.c
sysdeps/ieee754/ldbl-opt/w_sinh.c
sysdeps/ieee754/ldbl-opt/w_sinh.c
sysdeps/ieee754/ldbl-opt/w_atanh.c
sysdeps/ieee754/ldbl-opt/w_atanh.c
sysdeps/ieee754/ldbl-opt/s_cacosh.c
sysdeps/ieee754/ldbl-opt/s_cacosh.c
sysdeps/ieee754/ldbl-opt/s_catanh.c
sysdeps/ieee754/ldbl-opt/s_catanh.c
sysdeps/ieee754/ldbl-opt/s_cpow.c
sysdeps/ieee754/ldbl-opt/s_cpow.c
sysdeps/ieee754/ldbl-opt/s_catan.c
sysdeps/ieee754/ldbl-opt/s_catan.c
sysdeps/ieee754/ldbl-opt/s_erf.c
sysdeps/ieee754/ldbl-opt/s_erf.c
sysdeps/ieee754/ldbl-opt/s_erf.c
sysdeps/ieee754/ldbl-opt/s_round.c
sysdeps/ieee754/ldbl-opt/s_round.c
sysdeps/ieee754/ldbl-opt/w_acosh.c
sysdeps/ieee754/ldbl-opt/w_acosh.c
sysdeps/ieee754/ldbl-opt/s_scalbln.c
sysdeps/ieee754/ldbl-opt/s_scalbln.c
sysdeps/ieee754/ldbl-opt/s_scalbln.c
sysdeps/ieee754/ldbl-opt/s_scalbln.c
sysdeps/ieee754/ldbl-opt/s_ccosh.c
sysdeps/ieee754/ldbl-opt/s_ccosh.c
sysdeps/ieee754/ldbl-opt/s_scalbn.c
sysdeps/ieee754/ldbl-opt/s_scalbn.c
sysdeps/ieee754/ldbl-opt/s_scalbn.c
sysdeps/ieee754/ldbl-opt/s_scalbn.c
sysdeps/ieee754/ldbl-opt/w_acos.c
sysdeps/ieee754/ldbl-opt/w_acos.c
sysdeps/ieee754/ldbl-opt/w_fmod.c
sysdeps/ieee754/ldbl-opt/w_fmod.c
sysdeps/ieee754/ldbl-opt/s_llrint.c
sysdeps/ieee754/ldbl-opt/s_llrint.c
sysdeps/ieee754/ldbl-opt/w_tgamma.c
sysdeps/ieee754/ldbl-opt/w_tgamma.c
sysdeps/ieee754/ldbl-opt/s_log1p.c
sysdeps/ieee754/ldbl-opt/s_log1p.c
sysdeps/ieee754/ldbl-opt/cabs.c
sysdeps/ieee754/ldbl-opt/cabs.c
sysdeps/ieee754/ldbl-opt/Versions
sysdeps/ieee754/ldbl-opt/Versions
sysdeps/ieee754/ldbl-opt/s_modf.c
sysdeps/ieee754/ldbl-opt/s_modf.c
sysdeps/ieee754/ldbl-opt/s_modf.c
sysdeps/ieee754/ldbl-opt/s_modf.c
sysdeps/ieee754/ldbl-opt/s_trunc.c
sysdeps/ieee754/ldbl-opt/s_trunc.c
sysdeps/ieee754/ldbl-opt/s_ctanh.c
sysdeps/ieee754/ldbl-opt/s_ctanh.c
sysdeps/ieee754/ldbl-opt/s_tan.c
sysdeps/ieee754/ldbl-opt/s_tan.c
sysdeps/ieee754/ldbl-opt/s_tanh.c
sysdeps/ieee754/ldbl-opt/s_tanh.c
sysdeps/ieee754/ldbl-opt/s_lrint.c
sysdeps/ieee754/ldbl-opt/s_lrint.c
sysdeps/ieee754/ldbl-opt/conj.c
sysdeps/ieee754/ldbl-opt/conj.c
sysdeps/ieee754/ldbl-opt/s_cacos.c
sysdeps/ieee754/ldbl-opt/s_cacos.c
sysdeps/ieee754/ldbl-opt/s_logb.c
sysdeps/ieee754/ldbl-opt/s_logb.c
sysdeps/ieee754/ldbl-opt/w_scalb.c
sysdeps/ieee754/ldbl-opt/w_scalb.c
sysdeps/ieee754/ldbl-opt/s_significand.c
sysdeps/ieee754/ldbl-opt/s_significand.c
sysdeps/ieee754/ldbl-opt/s_ldexp.c
sysdeps/ieee754/ldbl-opt/s_ldexp.c
sysdeps/ieee754/ldbl-opt/s_ldexp.c
sysdeps/ieee754/ldbl-opt/s_ldexp.c
sysdeps/ieee754/ldbl-opt/s_casinh.c
sysdeps/ieee754/ldbl-opt/s_casinh.c
sysdeps/ieee754/ldbl-opt/s_sincos.c
sysdeps/ieee754/ldbl-opt/s_sincos.c
sysdeps/ieee754/ldbl-opt/s_llround.c
sysdeps/ieee754/ldbl-opt/s_llround.c
sysdeps/ieee754/ldbl-opt/w_log10.c
sysdeps/ieee754/ldbl-opt/w_log10.c
sysdeps/ieee754/ldbl-opt/s_fmin.c
sysdeps/ieee754/ldbl-opt/s_fmin.c
sysdeps/ieee754/ldbl-opt/w_hypot.c
sysdeps/ieee754/ldbl-opt/w_hypot.c
sysdeps/ieee754/ldbl-opt/s_nextafter.c
sysdeps/ieee754/ldbl-opt/s_nextafter.c
sysdeps/ieee754/ldbl-opt/s_nextafter.c
sysdeps/ieee754/ldbl-opt/s_nextafter.c
sysdeps/ieee754/ldbl-opt/s_nextafter.c
sysdeps/ieee754/ldbl-opt/s_nearbyint.c
sysdeps/ieee754/ldbl-opt/s_nearbyint.c
sysdeps/ieee754/ldbl-opt/w_drem.c
sysdeps/ieee754/ldbl-opt/w_drem.c
sysdeps/ieee754/ldbl-opt/s_atan.c
sysdeps/ieee754/ldbl-opt/s_atan.c
sysdeps/ieee754/ldbl-opt/s_ctan.c
sysdeps/ieee754/ldbl-opt/s_ctan.c
sysdeps/gnu/_G_config.h
sysdeps/gnu/_G_config.h
sysdeps/gnu/_G_config.h
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/gnu/siglist.c
sysdeps/unix/sysv/linux/posix_fadvise64.c
sysdeps/unix/sysv/linux/posix_fadvise64.c
sysdeps/unix/sysv/linux/posix_fadvise64.c
sysdeps/unix/sysv/linux/sparc/sparc64/Versions
sysdeps/unix/sysv/linux/sparc/sparc64/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/Versions
sysdeps/unix/sysv/linux/sparc/sparc32/nldbl-abi.h
sysdeps/unix/sysv/linux/sparc/sparc32/nldbl-abi.h
sysdeps/unix/sysv/linux/sparc/sparc32/Versions
sysdeps/unix/sysv/linux/sparc/sparc32/Versions
sysdeps/unix/sysv/linux/sparc/sparc32/Versions
sysdeps/unix/sysv/linux/sparc/sparc32/Versions
sysdeps/unix/sysv/linux/sparc/sparc32/semctl.c
sysdeps/unix/sysv/linux/sparc/sparc32/semctl.c
sysdeps/unix/sysv/linux/sparc/sparc32/semctl.c
sysdeps/unix/sysv/linux/sparc/sparc32/semctl.c
sysdeps/unix/sysv/linux/i386/getrlimit.c
sysdeps/unix/sysv/linux/i386/setrlimit.c
sysdeps/unix/sysv/linux/i386/getrlimit64.c
sysdeps/unix/sysv/linux/i386/getdents64.c
sysdeps/unix/sysv/linux/i386/readdir64_r.c
sysdeps/unix/sysv/linux/i386/readdir64_r.c
sysdeps/unix/sysv/linux/i386/readdir64_r.c
sysdeps/unix/sysv/linux/i386/versionsort64.c
sysdeps/unix/sysv/linux/i386/versionsort64.c
sysdeps/unix/sysv/linux/i386/versionsort64.c
sysdeps/unix/sysv/linux/i386/shmctl.c
sysdeps/unix/sysv/linux/i386/shmctl.c
sysdeps/unix/sysv/linux/i386/shmctl.c
sysdeps/unix/sysv/linux/i386/shmctl.c
sysdeps/unix/sysv/linux/i386/scandir64.c
sysdeps/unix/sysv/linux/i386/scandir64.c
sysdeps/unix/sysv/linux/i386/scandir64.c
sysdeps/unix/sysv/linux/i386/oldgetrlimit64.c
sysdeps/unix/sysv/linux/i386/oldgetrlimit64.c
sysdeps/unix/sysv/linux/i386/msgctl.c
sysdeps/unix/sysv/linux/i386/msgctl.c
sysdeps/unix/sysv/linux/i386/msgctl.c
sysdeps/unix/sysv/linux/i386/msgctl.c
sysdeps/unix/sysv/linux/i386/glob64.c
sysdeps/unix/sysv/linux/i386/glob64.c
sysdeps/unix/sysv/linux/i386/glob64.c
sysdeps/unix/sysv/linux/i386/posix_fadvise64.S
sysdeps/unix/sysv/linux/i386/posix_fadvise64.S
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/Versions
sysdeps/unix/sysv/linux/i386/readdir64.c
sysdeps/unix/sysv/linux/i386/readdir64.c
sysdeps/unix/sysv/linux/i386/readdir64.c
sysdeps/unix/sysv/linux/i386/semctl.c
sysdeps/unix/sysv/linux/i386/semctl.c
sysdeps/unix/sysv/linux/i386/semctl.c
sysdeps/unix/sysv/linux/i386/semctl.c
sysdeps/unix/sysv/linux/i386/chown.c
sysdeps/unix/sysv/linux/i386/chown.c
sysdeps/unix/sysv/linux/i386/chown.c
sysdeps/unix/sysv/linux/i386/chown.c
sysdeps/unix/sysv/linux/i386/chown.c
sysdeps/unix/sysv/linux/i386/syscalls.list
sysdeps/unix/sysv/linux/i386/syscalls.list
sysdeps/unix/sysv/linux/i386/syscalls.list
sysdeps/unix/sysv/linux/i386/syscalls.list
sysdeps/unix/sysv/linux/i386/alphasort64.c
sysdeps/unix/sysv/linux/i386/alphasort64.c
sysdeps/unix/sysv/linux/i386/alphasort64.c
sysdeps/unix/sysv/linux/fxstat64.c
sysdeps/unix/sysv/linux/fxstat64.c
sysdeps/unix/sysv/linux/fxstat64.c
sysdeps/unix/sysv/linux/wordsize-64/lio_listio.c
sysdeps/unix/sysv/linux/wordsize-64/lio_listio.c
sysdeps/unix/sysv/linux/wordsize-64/lio_listio.c
sysdeps/unix/sysv/linux/wordsize-64/Versions
sysdeps/unix/sysv/linux/configure.in
sysdeps/unix/sysv/linux/powerpc/configure.in
sysdeps/unix/sysv/linux/powerpc/powerpc32/posix_fadvise64.c
sysdeps/unix/sysv/linux/powerpc/powerpc32/posix_fadvise64.c
sysdeps/unix/sysv/linux/powerpc/powerpc32/posix_fadvise64.c
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc32/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc32/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc32/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc32/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/syscalls.list
sysdeps/unix/sysv/linux/powerpc/powerpc32/syscalls.list
sysdeps/unix/sysv/linux/powerpc/powerpc32/makecontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/makecontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/makecontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/makecontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc32/makecontext.S
sysdeps/unix/sysv/linux/powerpc/lchown.S
sysdeps/unix/sysv/linux/powerpc/lchown.S
sysdeps/unix/sysv/linux/powerpc/nldbl-abi.h
sysdeps/unix/sysv/linux/powerpc/nldbl-abi.h
sysdeps/unix/sysv/linux/powerpc/Versions
sysdeps/unix/sysv/linux/powerpc/chown.c
sysdeps/unix/sysv/linux/powerpc/powerpc64/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/setcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/swapcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc64/Versions
sysdeps/unix/sysv/linux/powerpc/powerpc64/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/getcontext.S
sysdeps/unix/sysv/linux/powerpc/powerpc64/getcontext.S
sysdeps/unix/sysv/linux/siglist.h
sysdeps/unix/sysv/linux/siglist.h
sysdeps/unix/sysv/linux/sched_getaffinity.c
sysdeps/unix/sysv/linux/sched_getaffinity.c
sysdeps/unix/sysv/linux/sched_getaffinity.c
sysdeps/unix/sysv/linux/sh/Versions
sysdeps/unix/sysv/linux/sh/Versions
sysdeps/unix/sysv/linux/sh/Versions
sysdeps/unix/sysv/linux/shmctl.c
sysdeps/unix/sysv/linux/shmctl.c
sysdeps/unix/sysv/linux/shmctl.c
sysdeps/unix/sysv/linux/shmctl.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmpx32.c
sysdeps/unix/sysv/linux/s390/s390-32/posix_fadvise64.c
sysdeps/unix/sysv/linux/s390/s390-32/posix_fadvise64.c
sysdeps/unix/sysv/linux/s390/s390-32/posix_fadvise64.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp32.c
sysdeps/unix/sysv/linux/s390/s390-32/login32.c
sysdeps/unix/sysv/linux/s390/s390-32/utmp-compat.h
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/Versions
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/chown.c
sysdeps/unix/sysv/linux/s390/s390-32/syscalls.list
sysdeps/unix/sysv/linux/s390/s390-32/syscalls.list
sysdeps/unix/sysv/linux/s390/nldbl-abi.h
sysdeps/unix/sysv/linux/s390/nldbl-abi.h
sysdeps/unix/sysv/linux/s390/s390-64/Versions
sysdeps/unix/sysv/linux/s390/Versions
sysdeps/unix/sysv/linux/s390/fpu/s_fma.c
sysdeps/unix/sysv/linux/s390/fpu/s_fma.c
sysdeps/unix/sysv/linux/xstat64.c
sysdeps/unix/sysv/linux/xstat64.c
sysdeps/unix/sysv/linux/xstat64.c
sysdeps/unix/sysv/linux/x86_64/Versions
sysdeps/unix/sysv/linux/x86_64/Versions
sysdeps/unix/sysv/linux/msgctl.c
sysdeps/unix/sysv/linux/msgctl.c
sysdeps/unix/sysv/linux/msgctl.c
sysdeps/unix/sysv/linux/msgctl.c
sysdeps/unix/sysv/linux/ia64/wordexp.c
sysdeps/unix/sysv/linux/ia64/wordexp.c
sysdeps/unix/sysv/linux/ia64/wordexp.c
sysdeps/unix/sysv/linux/ia64/Versions
sysdeps/unix/sysv/linux/ia64/Versions
sysdeps/unix/sysv/linux/ia64/Versions
sysdeps/unix/sysv/linux/ia64/Versions
sysdeps/unix/sysv/linux/sys/sysmacros.h
sysdeps/unix/sysv/linux/sched_setaffinity.c
sysdeps/unix/sysv/linux/sched_setaffinity.c
sysdeps/unix/sysv/linux/sched_setaffinity.c
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/Versions
sysdeps/unix/sysv/linux/lxstat64.c
sysdeps/unix/sysv/linux/lxstat64.c
sysdeps/unix/sysv/linux/lxstat64.c
sysdeps/unix/sysv/linux/semctl.c
sysdeps/unix/sysv/linux/semctl.c
sysdeps/unix/sysv/linux/semctl.c
sysdeps/unix/sysv/linux/semctl.c
sysdeps/unix/sysv/Versions
sysdeps/unix/bsd/bsd4.4/Versions
sysdeps/posix/posix_fallocate64.c
sysdeps/posix/posix_fallocate64.c
sysdeps/posix/posix_fallocate64.c
sysvipc/Versions
sysvipc/Versions
sysvipc/Versions
termios/Versions
termios/Versions
time/Versions
time/Versions
time/Versions
time/Versions
time/Versions
timezone/private.h
timezone/private.h
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
Versions.def
wcsmbs/Versions
wcsmbs/Versions
wcsmbs/Versions
wcsmbs/Versions
wcsmbs/wchar.h
wctype/Versions
wctype/Versions"

for f in $files
do
	sed -i 's/PEMU_LIBC/PEMU_LIBC/g' $f
done
