subdir   :=PEMU_plugins
routines :=plugin

#include ../../../build/config-host.mak
#PDEFINES=-I$(SRC_PATH)/target-i386/PEMU/PIN
#PDEFINES+=-D_GNU_SOURCE


#XED_PATH=$(SRC_PATH)/xed2/xed2-ia32/

#PCFLAGS=-w -Wall -g -fPIC -MMD -I$(XED_PATH)/include
#PLDFLAGS=-g -Wl,-E -shared -ldl 

#PLIBS+=-lm -L$(XED_PATH)/lib -lxed
#CFLAGS-plugin.c = $(PCFLAGS) $(PDEFINES)
#LDFLAGS-plugin = $(PLDFLAGS) $(PLIBS)

#include ../Rules
