/* This file is automatically generated by abi-versions.awk.
   It defines symbols used by shlib-compat.h, which see.  */

#ifndef _ABI_VERSIONS_H
#define _ABI_VERSIONS_H

/* start libBrokenLocale */
#define ABI_libBrokenLocale_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libBrokenLocale_PEMU_LIBC_2_0	PEMU_LIBC_2.0
/* end libBrokenLocale */

/* start libc */
#define ABI_libc_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libc_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libc_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_libc_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_libc_PEMU_LIBC_2_1_1	3	/* support PEMU_LIBC_2.1.1 */
#define VERSION_libc_PEMU_LIBC_2_1_1	PEMU_LIBC_2.1.1
#define ABI_libc_PEMU_LIBC_2_1_2	4	/* support PEMU_LIBC_2.1.2 */
#define VERSION_libc_PEMU_LIBC_2_1_2	PEMU_LIBC_2.1.2
#define ABI_libc_PEMU_LIBC_2_1_3	5	/* support PEMU_LIBC_2.1.3 */
#define VERSION_libc_PEMU_LIBC_2_1_3	PEMU_LIBC_2.1.3
#define ABI_libc_GLIBC_2_1_3	6	/* support GLIBC_2.1.3 */
#define VERSION_libc_GLIBC_2_1_3	GLIBC_2.1.3
#define ABI_libc_PEMU_LIBC_2_1_4	7	/* support PEMU_LIBC_2.1.4 */
#define VERSION_libc_PEMU_LIBC_2_1_4	PEMU_LIBC_2.1.4
#define ABI_libc_PEMU_LIBC_2_2	8	/* support PEMU_LIBC_2.2 */
#define VERSION_libc_PEMU_LIBC_2_2	PEMU_LIBC_2.2
#define ABI_libc_PEMU_LIBC_2_2_1	9	/* support PEMU_LIBC_2.2.1 */
#define VERSION_libc_PEMU_LIBC_2_2_1	PEMU_LIBC_2.2.1
#define ABI_libc_PEMU_LIBC_2_2_2	10	/* support PEMU_LIBC_2.2.2 */
#define VERSION_libc_PEMU_LIBC_2_2_2	PEMU_LIBC_2.2.2
#define ABI_libc_PEMU_LIBC_2_2_3	11	/* support PEMU_LIBC_2.2.3 */
#define VERSION_libc_PEMU_LIBC_2_2_3	PEMU_LIBC_2.2.3
#define ABI_libc_PEMU_LIBC_2_2_4	12	/* support PEMU_LIBC_2.2.4 */
#define VERSION_libc_PEMU_LIBC_2_2_4	PEMU_LIBC_2.2.4
#define ABI_libc_PEMU_LIBC_2_2_5	13	/* support PEMU_LIBC_2.2.5 */
#define VERSION_libc_PEMU_LIBC_2_2_5	PEMU_LIBC_2.2.5
#define ABI_libc_PEMU_LIBC_2_2_6	14	/* support PEMU_LIBC_2.2.6 */
#define VERSION_libc_PEMU_LIBC_2_2_6	PEMU_LIBC_2.2.6
#define ABI_libc_PEMU_LIBC_2_3	15	/* support PEMU_LIBC_2.3 */
#define VERSION_libc_PEMU_LIBC_2_3	PEMU_LIBC_2.3
#define ABI_libc_PEMU_LIBC_2_3_1	16	/* support PEMU_LIBC_2.3.1 */
#define VERSION_libc_PEMU_LIBC_2_3_1	PEMU_LIBC_2.3.1
#define ABI_libc_PEMU_LIBC_2_3_2	17	/* support PEMU_LIBC_2.3.2 */
#define VERSION_libc_PEMU_LIBC_2_3_2	PEMU_LIBC_2.3.2
#define ABI_libc_PEMU_LIBC_2_3_3	18	/* support PEMU_LIBC_2.3.3 */
#define VERSION_libc_PEMU_LIBC_2_3_3	PEMU_LIBC_2.3.3
#define ABI_libc_PEMU_LIBC_2_3_4	19	/* support PEMU_LIBC_2.3.4 */
#define VERSION_libc_PEMU_LIBC_2_3_4	PEMU_LIBC_2.3.4
#define ABI_libc_PEMU_LIBC_2_4	20	/* support PEMU_LIBC_2.4 */
#define VERSION_libc_PEMU_LIBC_2_4	PEMU_LIBC_2.4
#define ABI_libc_PEMU_LIBC_2_5	21	/* support PEMU_LIBC_2.5 */
#define VERSION_libc_PEMU_LIBC_2_5	PEMU_LIBC_2.5
#define ABI_libc_PEMU_LIBC_2_6	22	/* support PEMU_LIBC_2.6 */
#define VERSION_libc_PEMU_LIBC_2_6	PEMU_LIBC_2.6
#define ABI_libc_PEMU_LIBC_2_7	23	/* support PEMU_LIBC_2.7 */
#define VERSION_libc_PEMU_LIBC_2_7	PEMU_LIBC_2.7
#define ABI_libc_PEMU_LIBC_2_8	24	/* support PEMU_LIBC_2.8 */
#define VERSION_libc_PEMU_LIBC_2_8	PEMU_LIBC_2.8
#define ABI_libc_PEMU_LIBC_2_9	25	/* support PEMU_LIBC_2.9 */
#define VERSION_libc_PEMU_LIBC_2_9	PEMU_LIBC_2.9
#define ABI_libc_PEMU_LIBC_2_10	26	/* support PEMU_LIBC_2.10 */
#define VERSION_libc_PEMU_LIBC_2_10	PEMU_LIBC_2.10
#define ABI_libc_PEMU_LIBC_2_11	27	/* support PEMU_LIBC_2.11 */
#define VERSION_libc_PEMU_LIBC_2_11	PEMU_LIBC_2.11
#define ABI_libc_PEMU_LIBC_2_12	28	/* support PEMU_LIBC_2.12 */
#define VERSION_libc_PEMU_LIBC_2_12	PEMU_LIBC_2.12
#define ABI_libc_PEMU_LIBC_2_13	29	/* support PEMU_LIBC_2.13 */
#define VERSION_libc_PEMU_LIBC_2_13	PEMU_LIBC_2.13
#define ABI_libc_HURD_CTHREADS_0_3	30	/* support HURD_CTHREADS_0.3 */
#define VERSION_libc_HURD_CTHREADS_0_3	HURD_CTHREADS_0.3
#define ABI_libc_GCC_3_0	31	/* support GCC_3.0 */
#define VERSION_libc_GCC_3_0	GCC_3.0
#define ABI_libc_PEMU_LIBC_PRIVATE	32	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libc_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libc */

/* start libcrypt */
#define ABI_libcrypt_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libcrypt_PEMU_LIBC_2_0	PEMU_LIBC_2.0
/* end libcrypt */

/* start libdl */
#define ABI_libdl_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libdl_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libdl_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_libdl_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_libdl_PEMU_LIBC_2_3_3	3	/* support PEMU_LIBC_2.3.3 */
#define VERSION_libdl_PEMU_LIBC_2_3_3	PEMU_LIBC_2.3.3
#define ABI_libdl_PEMU_LIBC_2_3_4	4	/* support PEMU_LIBC_2.3.4 */
#define VERSION_libdl_PEMU_LIBC_2_3_4	PEMU_LIBC_2.3.4
/* end libdl */

/* start libm */
#define ABI_libm_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libm_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libm_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_libm_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_libm_PEMU_LIBC_2_2	3	/* support PEMU_LIBC_2.2 */
#define VERSION_libm_PEMU_LIBC_2_2	PEMU_LIBC_2.2
#define ABI_libm_PEMU_LIBC_2_2_3	4	/* support PEMU_LIBC_2.2.3 */
#define VERSION_libm_PEMU_LIBC_2_2_3	PEMU_LIBC_2.2.3
#define ABI_libm_PEMU_LIBC_2_3_4	5	/* support PEMU_LIBC_2.3.4 */
#define VERSION_libm_PEMU_LIBC_2_3_4	PEMU_LIBC_2.3.4
#define ABI_libm_PEMU_LIBC_2_4	6	/* support PEMU_LIBC_2.4 */
#define VERSION_libm_PEMU_LIBC_2_4	PEMU_LIBC_2.4
/* end libm */

/* start libnsl */
#define ABI_libnsl_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libnsl_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libnsl_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_libnsl_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_libnsl_PEMU_LIBC_2_2	3	/* support PEMU_LIBC_2.2 */
#define VERSION_libnsl_PEMU_LIBC_2_2	PEMU_LIBC_2.2
/* end libnsl */

/* start libnss_compat */
#define ABI_libnss_compat_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_compat_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_compat */

/* start libnss_dns */
#define ABI_libnss_dns_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_dns_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_dns */

/* start libnss_files */
#define ABI_libnss_files_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_files_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_files */

/* start libnss_hesiod */
#define ABI_libnss_hesiod_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_hesiod_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_hesiod */

/* start libnss_nis */
#define ABI_libnss_nis_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_nis_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_nis */

/* start libnss_nisplus */
#define ABI_libnss_nisplus_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libnss_nisplus_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libnss_nisplus */

/* start libpthread */
#define ABI_libpthread_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libpthread_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libpthread_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_libpthread_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_libpthread_PEMU_LIBC_2_1_1	3	/* support PEMU_LIBC_2.1.1 */
#define VERSION_libpthread_PEMU_LIBC_2_1_1	PEMU_LIBC_2.1.1
#define ABI_libpthread_PEMU_LIBC_2_1_2	4	/* support PEMU_LIBC_2.1.2 */
#define VERSION_libpthread_PEMU_LIBC_2_1_2	PEMU_LIBC_2.1.2
#define ABI_libpthread_PEMU_LIBC_2_2	5	/* support PEMU_LIBC_2.2 */
#define VERSION_libpthread_PEMU_LIBC_2_2	PEMU_LIBC_2.2
#define ABI_libpthread_PEMU_LIBC_2_2_3	6	/* support PEMU_LIBC_2.2.3 */
#define VERSION_libpthread_PEMU_LIBC_2_2_3	PEMU_LIBC_2.2.3
#define ABI_libpthread_PEMU_LIBC_2_2_6	7	/* support PEMU_LIBC_2.2.6 */
#define VERSION_libpthread_PEMU_LIBC_2_2_6	PEMU_LIBC_2.2.6
#define ABI_libpthread_PEMU_LIBC_2_3_2	8	/* support PEMU_LIBC_2.3.2 */
#define VERSION_libpthread_PEMU_LIBC_2_3_2	PEMU_LIBC_2.3.2
#define ABI_libpthread_PEMU_LIBC_2_3_3	9	/* support PEMU_LIBC_2.3.3 */
#define VERSION_libpthread_PEMU_LIBC_2_3_3	PEMU_LIBC_2.3.3
#define ABI_libpthread_PEMU_LIBC_2_3_4	10	/* support PEMU_LIBC_2.3.4 */
#define VERSION_libpthread_PEMU_LIBC_2_3_4	PEMU_LIBC_2.3.4
#define ABI_libpthread_PEMU_LIBC_2_4	11	/* support PEMU_LIBC_2.4 */
#define VERSION_libpthread_PEMU_LIBC_2_4	PEMU_LIBC_2.4
#define ABI_libpthread_PEMU_LIBC_2_6	12	/* support PEMU_LIBC_2.6 */
#define VERSION_libpthread_PEMU_LIBC_2_6	PEMU_LIBC_2.6
#define ABI_libpthread_PEMU_LIBC_2_11	13	/* support PEMU_LIBC_2.11 */
#define VERSION_libpthread_PEMU_LIBC_2_11	PEMU_LIBC_2.11
#define ABI_libpthread_PEMU_LIBC_2_12	14	/* support PEMU_LIBC_2.12 */
#define VERSION_libpthread_PEMU_LIBC_2_12	PEMU_LIBC_2.12
#define ABI_libpthread_PEMU_LIBC_PRIVATE	15	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libpthread_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libpthread */

/* start libresolv */
#define ABI_libresolv_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libresolv_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libresolv_PEMU_LIBC_2_2	2	/* support PEMU_LIBC_2.2 */
#define VERSION_libresolv_PEMU_LIBC_2_2	PEMU_LIBC_2.2
#define ABI_libresolv_PEMU_LIBC_2_3_2	3	/* support PEMU_LIBC_2.3.2 */
#define VERSION_libresolv_PEMU_LIBC_2_3_2	PEMU_LIBC_2.3.2
#define ABI_libresolv_PEMU_LIBC_2_9	4	/* support PEMU_LIBC_2.9 */
#define VERSION_libresolv_PEMU_LIBC_2_9	PEMU_LIBC_2.9
#define ABI_libresolv_PEMU_LIBC_PRIVATE	5	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libresolv_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libresolv */

/* start librt */
#define ABI_librt_PEMU_LIBC_2_1	1	/* support PEMU_LIBC_2.1 */
#define VERSION_librt_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_librt_PEMU_LIBC_2_2	2	/* support PEMU_LIBC_2.2 */
#define VERSION_librt_PEMU_LIBC_2_2	PEMU_LIBC_2.2
#define ABI_librt_PEMU_LIBC_2_3	3	/* support PEMU_LIBC_2.3 */
#define VERSION_librt_PEMU_LIBC_2_3	PEMU_LIBC_2.3
#define ABI_librt_PEMU_LIBC_2_3_3	4	/* support PEMU_LIBC_2.3.3 */
#define VERSION_librt_PEMU_LIBC_2_3_3	PEMU_LIBC_2.3.3
#define ABI_librt_PEMU_LIBC_2_3_4	5	/* support PEMU_LIBC_2.3.4 */
#define VERSION_librt_PEMU_LIBC_2_3_4	PEMU_LIBC_2.3.4
#define ABI_librt_PEMU_LIBC_2_4	6	/* support PEMU_LIBC_2.4 */
#define VERSION_librt_PEMU_LIBC_2_4	PEMU_LIBC_2.4
#define ABI_librt_PEMU_LIBC_2_7	7	/* support PEMU_LIBC_2.7 */
#define VERSION_librt_PEMU_LIBC_2_7	PEMU_LIBC_2.7
/* end librt */

/* start libutil */
#define ABI_libutil_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_libutil_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_libutil_PEMU_LIBC_2_9	2	/* support PEMU_LIBC_2.9 */
#define VERSION_libutil_PEMU_LIBC_2_9	PEMU_LIBC_2.9
/* end libutil */

/* start ld */
#define ABI_ld_PEMU_LIBC_2_0	1	/* support PEMU_LIBC_2.0 */
#define VERSION_ld_PEMU_LIBC_2_0	PEMU_LIBC_2.0
#define ABI_ld_PEMU_LIBC_2_1	2	/* support PEMU_LIBC_2.1 */
#define VERSION_ld_PEMU_LIBC_2_1	PEMU_LIBC_2.1
#define ABI_ld_PEMU_LIBC_2_3	3	/* support PEMU_LIBC_2.3 */
#define VERSION_ld_PEMU_LIBC_2_3	PEMU_LIBC_2.3
#define ABI_ld_PEMU_LIBC_2_4	4	/* support PEMU_LIBC_2.4 */
#define VERSION_ld_PEMU_LIBC_2_4	PEMU_LIBC_2.4
#define ABI_ld_PEMU_LIBC_PRIVATE	5	/* support PEMU_LIBC_PRIVATE */
#define VERSION_ld_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end ld */

/* start libthread_db */
#define ABI_libthread_db_PEMU_LIBC_2_1_3	1	/* support PEMU_LIBC_2.1.3 */
#define VERSION_libthread_db_PEMU_LIBC_2_1_3	PEMU_LIBC_2.1.3
#define ABI_libthread_db_PEMU_LIBC_2_2_3	2	/* support PEMU_LIBC_2.2.3 */
#define VERSION_libthread_db_PEMU_LIBC_2_2_3	PEMU_LIBC_2.2.3
#define ABI_libthread_db_PEMU_LIBC_2_3	3	/* support PEMU_LIBC_2.3 */
#define VERSION_libthread_db_PEMU_LIBC_2_3	PEMU_LIBC_2.3
#define ABI_libthread_db_PEMU_LIBC_2_3_3	4	/* support PEMU_LIBC_2.3.3 */
#define VERSION_libthread_db_PEMU_LIBC_2_3_3	PEMU_LIBC_2.3.3
/* end libthread_db */

/* start libanl */
#define ABI_libanl_PEMU_LIBC_2_2_3	1	/* support PEMU_LIBC_2.2.3 */
#define VERSION_libanl_PEMU_LIBC_2_2_3	PEMU_LIBC_2.2.3
/* end libanl */

/* start libcidn */
#define ABI_libcidn_PEMU_LIBC_PRIVATE	1	/* support PEMU_LIBC_PRIVATE */
#define VERSION_libcidn_PEMU_LIBC_PRIVATE	PEMU_LIBC_PRIVATE
/* end libcidn */

#endif /* abi-versions.h */
